#!/usr/bin/env python3

import json
import sys
import subprocess

status = {}
try:
    result = subprocess.run(['podman', 'ps', '--filter', 'name=qdrant', '--format', '{{.State}}'], capture_output=True, text=True, check=True)
    status['active'] = 'running' in result.stdout.lower()
except (subprocess.CalledProcessError, FileNotFoundError):
    status['active'] = False

json.dump(status, fp=sys.stdout)
