#!/usr/bin/env python3

import json
import sys
import subprocess

try:
    subprocess.run([
        'systemctl', '--user', 'restart', 'qdrant.service'
    ], check=True)
    
    json.dump({"service_restarted": True}, fp=sys.stdout)
except subprocess.CalledProcessError as e:
    json.dump({
        "service_restarted": False,
        "error": str(e)
    }, fp=sys.stdout)
    sys.exit(1)
