#!/usr/bin/env python3

import json
import sys
import subprocess

try:
    subprocess.run([
        'systemctl', '--user', 'start', 'qdrant'
    ], check=True)
    
    json.dump({"service_started": True}, fp=sys.stdout)
except subprocess.CalledProcessError as e:
    json.dump({
        "service_started": False,
        "error": str(e)
    }, fp=sys.stdout)
    sys.exit(1)
