#!/bin/bash

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

# Enable and start the Qdrant service

systemctl --user enable qdrant.service
systemctl --user start qdrant.service
