#!/usr/bin/env python3

import json
import sys
import subprocess

try:
    subprocess.run([
        'systemctl', '--user', 'stop', 'qdrant.service'
    ], check=True)
    
    json.dump({"service_stopped": True}, fp=sys.stdout)
except subprocess.CalledProcessError as e:
    json.dump({
        "service_stopped": False,
        "error": str(e)
    }, fp=sys.stdout)
    sys.exit(1)
