#!/usr/bin/env python3

#
# Copyright (C) 2025 Lee M. Lwando
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

config = {
    "http_port": int(agent.get_env('HTTP_PORT', '6333')),
    "grpc_port": int(agent.get_env('GRPC_PORT', '6334')),
    "api_key_set": bool(agent.get_env('QDRANT__SERVICE__API_KEY', ''))
}

json.dump(config, fp=sys.stdout)
