#!/usr/bin/env python3

import json
import sys
import os

# Read current configuration
config_file = os.environ.get('AGENT_STATE_DIR', '.') + '/config.json'
default_config = {
    "host": "",
    "path": "",
    "lets_encrypt": False,
    "http_to_https": False,
    "port": 6333,
    "api_key": "",
    "collection_size_limit": 10000,
    "enable_cors": True
}

try:
    with open(config_file, 'r') as f:
        config = json.load(f)
except FileNotFoundError:
    config = default_config

json.dump({"configuration": config}, fp=sys.stdout)
