name: Build and publish module images

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
      - master

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Buildah
        id: buildah-build
        env:
          REPOBASE: ${{ env.REGISTRY }}/${{ github.repository_owner }}
          IMAGETAG: ${{ github.sha }}
          CI: 1
        run: |
          # Install buildah
          sudo apt-get update
          sudo apt-get install -y buildah

          # Make build script executable
          chmod +x build-images.sh

          # Run the build script
          ./build-images.sh

      - name: Push images
        env:
          REPOBASE: ${{ env.REGISTRY }}/${{ github.repository_owner }}
          IMAGETAG: ${{ github.sha }}
        run: |
          if [[ -n "${{ steps.buildah-build.outputs.images }}" ]]; then
            for image in ${{ steps.buildah-build.outputs.images }}; do
              buildah push \
                --digestfile=/tmp/digestfile \
                "$image" \
                "docker://$image:$IMAGETAG"

              # Also push as latest on main/master branch
              if [[ "${{ github.ref }}" == "refs/heads/main" || "${{ github.ref }}" == "refs/heads/master" ]]; then
                buildah push "$image" "docker://$image:latest"
              fi

              # Push tags
              if [[ "${{ github.ref }}" == refs/tags/* ]]; then
                tag=${GITHUB_REF#refs/tags/}
                buildah push "$image" "docker://$image:$tag"
              fi
            done
          fi

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/ns8-qdrant

      - name: Show summary
        run: |
          echo "## Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Images built:**" >> $GITHUB_STEP_SUMMARY
          for image in ${{ steps.buildah-build.outputs.images }}; do
            echo "- \`$image:${{ github.sha }}\`" >> $GITHUB_STEP_SUMMARY
            if [[ "${{ github.ref }}" == "refs/heads/main" || "${{ github.ref }}" == "refs/heads/master" ]]; then
              echo "- \`$image:latest\`" >> $GITHUB_STEP_SUMMARY
            fi
          done
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Installation command:**" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`bash" >> $GITHUB_STEP_SUMMARY
          echo "add-module ${{ env.REGISTRY }}/${{ github.repository_owner }}/ns8-qdrant:latest 1" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY