name: Build and push module image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up buildah
        run: |
          sudo apt-get update
          sudo apt-get install -y buildah

      - name: Log in to the Container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build images
        run: |
          chmod +x build-images.sh
          ./build-images.sh

      - name: Push images to registry
        if: github.event_name != 'pull_request'
        run: |
          readarray -t images <<<"$(echo "${{ env.IMAGES }}" | tr ' ' '\n')"
          for image in "${images[@],,}"; do
            buildah push "$image" docker://"$image":${GITHUB_REF_NAME/\//-}
            if [[ "$GITHUB_REF_TYPE" == "tag" ]]; then
              buildah tag "$image" "$image":latest
              buildah push "$image" docker://"$image":latest
            fi
          done
