name: Clean registry

on:
  schedule:
    # Run weekly on Sundays at 2 AM UTC
    - cron: '0 2 * * 0'
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run (do not actually delete)'
        required: false
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

env:
  REGISTRY: ghcr.io

jobs:
  clean-registry:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Delete old container images
        uses: actions/delete-package-versions@v4
        with:
          package-name: 'ns8-qdrant'
          package-type: 'container'
          min-versions-to-keep: 10
          delete-only-untagged-versions: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean up old pre-release versions
        uses: actions/delete-package-versions@v4
        with:
          package-name: 'ns8-qdrant' 
          package-type: 'container'
          min-versions-to-keep: 5
          delete-only-pre-release-versions: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Summary
        run: |
          echo "## Registry Cleanup Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- Kept latest 10 versions" >> $GITHUB_STEP_SUMMARY
          echo "- Removed untagged versions" >> $GITHUB_STEP_SUMMARY  
          echo "- Kept latest 5 pre-release versions" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Current images available at: \`${{ env.REGISTRY }}/${{ github.repository_owner }}/ns8-qdrant\`" >> $GITHUB_STEP_SUMMARY