name: Test module

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ui/package-lock.json

      - name: Install UI dependencies
        working-directory: ./ui
        run: npm ci

      - name: Run UI tests
        working-directory: ./ui
        run: |
          # Add your UI tests here
          npm run test --if-present
          npm run lint --if-present

      - name: Build UI
        working-directory: ./ui
        run: npm run build

      - name: Validate imageroot structure
        run: |
          # Check required directories exist
          test -d imageroot/actions || (echo "Missing imageroot/actions directory" && exit 1)
          test -d imageroot/systemd/user || (echo "Missing imageroot/systemd/user directory" && exit 1)
          
          # Check required action scripts exist
          test -f imageroot/actions/create-module/10initialize || (echo "Missing create-module action" && exit 1)
          test -f imageroot/actions/configure-module/10configure || (echo "Missing configure-module action" && exit 1)
          test -f imageroot/actions/destroy-module/10destroy || (echo "Missing destroy-module action" && exit 1)
          
          # Check systemd service file exists
          test -f imageroot/systemd/user/qdrant.service || (echo "Missing qdrant.service file" && exit 1)
          
          echo "✅ All required files and directories found"

      - name: Check Python syntax
        run: |
          # Install Python for syntax checking
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          
          # Check Python files for syntax errors
          find imageroot -name "*.py" -exec python3 -m py_compile {} \;
          echo "✅ Python syntax check passed"

      - name: Validate build script
        run: |
          # Check build script exists and is executable
          test -f build-images.sh || (echo "Missing build-images.sh" && exit 1)
          test -x build-images.sh || (echo "build-images.sh is not executable" && exit 1)
          
          # Basic syntax check
          bash -n build-images.sh
          echo "✅ Build script validation passed"