name: Test module

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.15.0

      - name: Install UI dependencies
        working-directory: ./ui
        run: pnpm install

      - name: Build UI
        working-directory: ./ui
        run: pnpm run build

      - name: Validate imageroot structure
        run: |
          # Check required directories exist
          test -d imageroot/actions || (echo "Missing imageroot/actions directory" && exit 1)
          test -d imageroot/systemd/user || (echo "Missing imageroot/systemd/user directory" && exit 1)
          
          # Check required action scripts exist
          test -f imageroot/actions/create-module/10initialize || (echo "Missing create-module initialization" && exit 1)
          test -f imageroot/actions/configure-module/10validate || (echo "Missing configure-module validation" && exit 1)
          test -f imageroot/actions/configure-module/20configure || (echo "Missing configure-module action" && exit 1)
          test -f imageroot/actions/get-configuration/20read || (echo "Missing get-configuration action" && exit 1)
          test -f imageroot/actions/get-status/20read || (echo "Missing get-status action" && exit 1)
          test -f imageroot/actions/destroy-module/10destroy || (echo "Missing destroy-module action" && exit 1)
          
          # Check systemd service file exists
          test -f imageroot/systemd/user/qdrant.service || (echo "Missing qdrant.service file" && exit 1)
          
          echo "✅ All required files and directories found"

      - name: Check Python syntax
        run: |
          # Install Python for syntax checking
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          
          # Check Python files for syntax errors
          find imageroot -name "*.py" -exec python3 -m py_compile {} \;
          echo "✅ Python syntax check passed"

      - name: Validate build script
        run: |
          # Check build script exists and is executable
          test -f build-images.sh || (echo "Missing build-images.sh" && exit 1)
          test -x build-images.sh || (echo "build-images.sh is not executable" && exit 1)
          
          # Basic syntax check
          bash -n build-images.sh
          echo "✅ Build script validation passed"

      - name: Validate metadata
        run: |
          # Check metadata.json exists and is valid JSON
          test -f metadata.json || (echo "Missing metadata.json" && exit 1)
          python3 -m json.tool metadata.json > /dev/null || (echo "Invalid JSON in metadata.json" && exit 1)
          echo "✅ Metadata validation passed"